### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by nhiepphong** [karamsa/android-radar#1]
Hi bro,

I just use your library.
I like it.
Thanks bro.

But. I want radar have detect direction. If i rotation my phone, the radar will change direction.

I see your code:

void drawPins(Location referenceLocation, ArrayList<Location> locations, int pxCanvas, int metterDistance)

And i see: int angle = rand.nextInt(360)+1;

Can you help me ?

Thanks bro very much.

**Comment by karamsa** [comment]
Hello,  
thank you for using this library.
When i get points i put them randomly on the radar.
This is why i used "int angle = rand.nextInt(360)+1" 
Untile now this is not supporting diriction :(
Thanks

**Comment by nhiepphong** [comment]
Hi karamsa,
I just done it.

Thanks

**Comment by karamsa** [comment]
HI thank you for your answer,
Please share code for direction or make a fork if you can.
Thanks
