### ISSUE TITLE
Importing the module

### ISSUE THREAD

**Issue by phillipsgoncalves** [karamsa/android-radar#2]
Hello, sorry for opening a ticket for this, but i don't have another way to contact you.
While importing the module you say to choose the folder radar. What folder radar are you talking about  ? The one inside the java folder? That one will not have the graddle file, so it will fail.

I am sorry, but i am new to Android and i am trying to use your library.

Thank you !

**Comment by karamsa** [comment]
Hello, 
Thank you for contacting me.
1) Please dowload the zip and extract folder.
2) There is only one folder on the root. The folder is "android-radar-master"
3) import it and add  compile project(':android-radar-master')
Hope this will help you

**Comment by karamsa** [comment]
I updated the the Readme

**Comment by phillipsgoncalves** [comment]
Thank you very much for the explanation. I wasn't expecting you to answer me. Thank you a lot for your help and your awesome work !
