### ISSUE TITLE
How to move points on radar to radially outwards on seek bar change 

### ISSUE THREAD

**Issue by tusharuit25** [karamsa/android-radar#4]
Please guide for extension in your component

**Comment by karamsa** [comment]
If you mean to change the distance covered by the radar: you can change the property maxDistance of the Radar class,  the default value is 10000 meter.

**Comment by tusharuit25** [comment]
No I mean Like this example https://github.com/abm-adnan/Radar ?

**Comment by karamsa** [comment]
Ah sorry this is not supported yet. thanks
